# Generated by Django 5.0.6 on 2024-12-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_ngo_details_u_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_details',
            old_name='u_id',
            new_name='n_id',
        ),
    ]
