# Generated by Django 5.0.6 on 2024-12-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_rename_u_id_ngo_details_n_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_details',
            old_name='n_id',
            new_name='ngo_id',
        ),
    ]
