# Generated by Django 5.1.4 on 2024-12-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_n_id_ngo_details_ngo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='ngo_id',
            field=models.ForeignKey(db_column='ngo', null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.ngo_details'),
        ),
    ]
